### ISSUE TITLE
Missing inkscape

### ISSUE THREAD

**Issue by jacksgt** [aergus/dockerfiles#4]
Hi there,

I know you haven't pushed anything to this repo since [May 10](https://github.com/aergus/dockerfiles/commit/5e2f4dbb26914235612925b835e58d419272d11d), but still there is a new build from 4 days ago on DockerHub: https://hub.docker.com/r/aergus/latex/builds/

Anyway, since this build my CI jobs fail due to missing inkscape package. It was definitely present before.

```
make thesis.pdf
inkscape -A images/apic-architecture.pdf images/apic-architecture.svg
make: inkscape: Command not found
make: *** [Makefile:26: images/apic-architecture.pdf] Error 127
ERROR: Job failed: exit code 1
```

Regards
Jack

**Comment by aergus** [comment]
I try to build the image regularly because the software on Debian testing gets updated fairly frequently. (After all, getting more up to date TeX Live packages was the main reason for using testing.)

The Dockerfile did indeed stay the same since May, but the dependencies in Debian might have changed, resulting in some packages which were previously installed as dependencies being missing now. However, I checked the logs of last few builds on Docker Hub and all of them listed Inkscape not as a package to be installed, but just as a "suggested package", so I have no idea how Inkscape snuck in to the image you have been using.

In any case, I don't think that Inkscape belongs to this image, mainly because it would introduce too much bloat as it depends on things like GTK, so I don't want to add it as a package to be installed. I guess you'll need to maintain a separate dockerfile if you really need Inkscape.

**Comment by jacksgt** [comment]
Hi, thanks a lot for your investigation!

If you do want to add inkscape to the image that's fine and I respect that decision (after all, you need to draw the line somewhere), but the inkscape does not pull that many dependencies (run in `aergus/latex` container)
```
$ apt install inkscape
The following NEW packages will be installed:
  aspell aspell-en dictionaries-common enchant fig2dev gawk hunspell-en-us inkscape libaspell15 libatkmm-1.6-1v5 libblas3 libcairomm-1.0-1v5 libcdr-0.1-1 libdbus-glib-1-2 libenchant1c2a libgail-common libgail18
  libgfortran5 libglibmm-2.4-1v5 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libgtkmm-2.4-1v5 libgtkspell0 libhunspell-1.6-0 libimage-magick-perl libimage-magick-q16-perl liblapack3 libpangomm-1.4-1v5 libpopt0
  libquadmath0 librevenge-0.0-0 libsigc++-2.0-0v5 libvisio-0.1-1 libwmf-bin libwpd-0.10-10 libwpg-0.3-3 python-bs4 python-html5lib python-lxml python-numpy python-scour python-six python-webencodings
  python3-pkg-resources python3-scour python3-six scour
0 upgraded, 48 newly installed, 0 to remove and 164 not upgraded.
Need to get 32.8 MB of archives.
After this operation, 158 MB of additional disk space will be used.
```

```
$ apt install --no-install-recommends inkscape
Recommended packages:
  libimage-magick-perl libwmf-bin python-lxml python-numpy python-scour transfig enchant libgail-common libgtk2.0-bin hunspell-en-us | hunspell-dictionary | myspell-dictionary
The following NEW packages will be installed:
  aspell aspell-en dictionaries-common inkscape libaspell15 libatkmm-1.6-1v5 libcairomm-1.0-1v5 libcdr-0.1-1 libdbus-glib-1-2 libenchant1c2a libglibmm-2.4-1v5 libgtk2.0-0 libgtk2.0-common libgtkmm-2.4-1v5
  libgtkspell0 libhunspell-1.6-0 libpangomm-1.4-1v5 libpopt0 librevenge-0.0-0 libsigc++-2.0-0v5 libvisio-0.1-1 libwpd-0.10-10 libwpg-0.3-3
0 upgraded, 23 newly installed, 0 to remove and 164 not upgraded.
Need to get 23.9 MB of archives.
After this operation, 124 MB of additional disk space will be used.
```

**Comment by aergus** [comment]
Thanks for the demonstration, but >100MB looks like a significant portion of the image size and I still think that the image is better off without Inkscape.

**Comment by jacksgt** [comment]
Ok, fair enough. I'm closing this issue then.
