### ISSUE TITLE
Consider adding Java

### ISSUE THREAD

**Issue by A6GibKm** [aergus/dockerfiles#7]
I am using this image to run `arara` on tex files for my personal website. `arara` depends on java which is not in the image, I have to add
`apt install -y default-jre` as a solution to my CI.

**Comment by aergus** [comment]
Thanks for reporting this. I've added the "headless" version of JRE in a478ebb307add4b0e2ccdc8eb4fe3edd9c9f7659. If you are using the Docher Hub image, that's updated as well. Can you confirm that `arara` is working as expected?

This causes a rather large overhead (~170 MB), but I think there is no way around it because there is at least one more tool listed in [`texlive-extra-utils`](https://packages.debian.org/bullseye/texlive-extra-utils) (namely `texosquery`) that seems to require Java. I'm actually a bit surprised that JRE is not a dependency or at least a suggested package for `texlive-extra-utils`, so maybe I'll contact the maintainers.

**Comment by A6GibKm** [comment]
`arara` now opens fine. Thanks for the quick response.
